const sb=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);let user=null,selected=null,realtime=null,mode="login";
const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));$(id).classList.remove("hidden");if(id==="discover")loadProfiles();if(id==="matches")loadMatches();if(id==="messages")loadChatUsers();if(id==="profile")loadMyProfile();history.replaceState(null,"","#"+id)}
function authMode(m){mode=m;$("loginTab").classList.toggle("active",m==="login");$("signupTab").classList.toggle("active",m==="signup");$("signupFields").classList.toggle("hidden",m==="login");$("authBtn").textContent=m==="login"?"Log in":"Create account"}
async function submitAuth(e){e.preventDefault();$("authMsg").textContent="";const email=$("email").value.trim(),password=$("password").value;let r;if(mode==="login")r=await sb.auth.signInWithPassword({email,password});else{const age=Number($("age").value);if(age<18)return $("authMsg").textContent="You must be 18 or older.";r=await sb.auth.signUp({email,password});if(!r.error&&r.data.user)await sb.from("profiles").insert({id:r.data.user.id,name:$("name").value,age,city:$("city").value,bio:$("bio").value,interests:[]});}if(r.error)$("authMsg").textContent=r.error.message;else if(mode==="signup")$("authMsg").textContent="Account created. Check your email if confirmation is enabled."}
async function boot(){const {data}=await sb.auth.getSession();user=data.session?.user||null;if(user){$("auth").classList.add("hidden");$("nav").classList.remove("hidden");show(location.hash.slice(1)||"discover");await updateCount()}else{show("auth")}sb.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;if(!user){$("nav").classList.add("hidden");$("auth").classList.remove("hidden");show("auth")}})}
async function logout(){await sb.auth.signOut()}
async function loadProfiles(){if(!user)return;let q=sb.from("profiles").select("*").neq("id",user.id).eq("is_blocked",false).limit(60);const f=$("filter").value;if(f!=="all")q=q.contains("interests",[f]);const {data,error}=await q;const box=$("profiles");if(error)return box.innerHTML=`<div class="empty">${error.message}</div>`;const {data:likes}=await sb.from("likes").select("to_user").eq("from_user",user.id);const liked=new Set((likes||[]).map(x=>x.to_user));const list=(data||[]).filter(p=>!liked.has(p.id));box.innerHTML=list.length?list.map(card).join(""):`<div class="empty">No more profiles found. Try another interest.</div>`}
function card(p){const tags=(p.interests||[]).map(x=>`<span class="tag">${escape(x)}</span>`).join("");const img=p.avatar_url||"https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=700&q=80";return `<article class="profile"><img src="${img}" alt=""><div class="body"><h3>${escape(p.name)}, ${p.age}</h3><div class="muted">${escape(p.city||"")}</div><p>${escape(p.bio||"")}</p><div class="tags">${tags}</div><div class="actions"><button class="pass" onclick="like(${p.id},false)">Pass</button><button class="like" onclick="like(${p.id},true)">Like ♥</button></div><div class="tools"><button class="link" onclick="reportUser('${p.id}')">Report</button><button class="link" onclick="blockUser('${p.id}')">Block</button></div></div></article>`}
async function like(id,want){await sb.from("likes").upsert({from_user:user.id,to_user:id},{onConflict:"from_user,to_user"});if(want){const {data}=await sb.from("likes").select("from_user").eq("from_user",id).eq("to_user",user.id).maybeSingle();if(data)alert("It's a match!")}await updateCount();loadProfiles()}
async function loadMatches(){const {data,error}=await sb.from("matches").select("id,user_a,user_b,other:other_profile(*)");const box=$("matchesList");if(error)return box.innerHTML=`<div class="empty">${error.message}</div>`;box.innerHTML=(data||[]).length?data.map(m=>`<div class="card" style="padding:18px;text-align:center"><h3>${escape(m.other?.name||"Match")}</h3><p class="muted">${escape(m.other?.city||"")}</p><button class="primary" onclick="openChat('${m.other.id}')">Message</button></div>`).join(""):`<div class="empty">Mutual matches will appear here.</div>`}
async function loadChatUsers(){const {data}=await sb.from("matches").select("other:other_profile(*)");$("chatUsers").innerHTML=(data||[]).map(x=>`<button class="person ${selected===x.other.id?"active":""}" onclick="openChat('${x.other.id}')"><img src="${x.other.avatar_url||'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=70'}"><span><b>${escape(x.other.name)}</b><br><small>${escape(x.other.city||"")}</small></span></button>`).join("")||`<div class="empty">No matches yet.</div>`;if(selected)loadMessages()}
async function openChat(id){selected=id;show("messages");await loadChatUsers();await loadMessages()}
async function loadMessages(){if(!selected)return;const {data:p}=await sb.from("profiles").select("*").eq("id",selected).single();$("chatTitle").textContent=p?`${p.name}, ${p.age} · ${p.city||""}`:"Chat";const {data}=await sb.from("messages").select("*").or(`and(sender_id.eq.${user.id},receiver_id.eq.${selected}),and(sender_id.eq.${selected},receiver_id.eq.${user.id})`).order("created_at");$("chatLog").innerHTML=(data||[]).map(m=>`<div class="bubble ${m.sender_id===user.id?"me":"them"}">${escape(m.body)}</div>`).join("");if(realtime)sb.removeChannel(realtime);realtime=sb.channel("chat-"+[user.id,selected].sort().join("-")).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages"},payload=>{const m=payload.new;if((m.sender_id===user.id&&m.receiver_id===selected)||(m.sender_id===selected&&m.receiver_id===user.id))loadMessages()}).subscribe()}
async function sendMessage(e){e.preventDefault();const body=$("message").value.trim();if(!body||!selected)return;const {error}=await sb.from("messages").insert({sender_id:user.id,receiver_id:selected,body});if(error)alert(error.message);else{$("message").value="";loadMessages()}}
async function loadMyProfile(){const {data}=await sb.from("profiles").select("*").eq("id",user.id).single();if(!data)return;$("pname").value=data.name||"";$("page").value=data.age||18;$("pcity").value=data.city||"";$("pbio").value=data.bio||"";$("pinterests").value=(data.interests||[]).join(", ")}
async function saveProfile(e){e.preventDefault();const interests=$("pinterests").value.split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);const {error}=await sb.from("profiles").update({name:$("pname").value,age:Number($("page").value),city:$("pcity").value,bio:$("pbio").value,interests}).eq("id",user.id);alert(error?error.message:"Profile saved.")}
async function updateCount(){const {count}=await sb.from("matches").select("*",{count:"exact",head:true});$("matchCount").textContent=count||0}
async function blockUser(id){await sb.from("blocks").upsert({blocker_id:user.id,blocked_id:id});alert("User blocked.");loadProfiles()}
async function reportUser(id){const reason=prompt("Reason for report:");if(reason)await sb.from("reports").insert({reporter_id:user.id,reported_id:id,reason});alert("Report submitted.")}
function escape(s=""){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
boot();